name: child1
# Changed 'on' to enable this workflow to be called from other workflows
on:
  push

jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: heidemann78/actions-learning-pathway/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
